print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")

#\n untuk memberikan newline
print("    *\n   * *\n  *   *\n *     *\n***   ***\n  *   *\n  *   *\n  *****")

print("    *    ", "    *")
print("   * *   ", "   * *")
print("  *   *  ", "  *   *")
print(" *     * ", " *     *")
print("***   ***", "***   ***")
print("  *   *  ", "  *   *")
print("  *   *  ", "  *   *")
print("  *****  ", "  *****")

#sep untuk memberikan separator antara variabel yg diprint
print("    *    ", "    *", sep=" ")
print("   * *   ", "   * *", sep=" ")
print("  *   *  ", "  *   *", sep=" ")
print(" *     * ", " *     *", sep=" ")
print("***   ***", "***   ***", sep=" ")
print("  *   *  ", "  *   *", sep=" ")
print("  *   *  ", "  *   *", sep=" ")
print("  *****  ", "  *****", sep=" ")

print('    *     '*3)
print('   * *    '*3)
print('  *   *   '*3)
print(' *     *  '*3)
print('***   *** '*3)
print('  *   *   '*3)
print('  *   *   '*3)
print('  *****   '*3)
